version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: 'elasticsearch'
    environment:
      - discovery.type=single-node
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    working_dir: /var/www/symfony
    restart: always
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  elastic:
    driver: local